migrate to cp3pt0
IBM/ibm-common-service-operator pull request #1082
Opened 2023-03-16 15:28 UTC by Daniel-Fan

2023-03-23 20:27 UTC, bitscuit requested changes

2023-03-23 20:27 UTC, bitscuit commented on cp3pt0-deployment/migrate_tenant.sh
> +    wait_for_operator "$OPERATOR_NS" "ibm-common-service-operator"
Can we wait for subscription.status.state == AtLatestKnown instead of waiting for operator, so that the `sleep` can be removed?

2023-03-23 20:39 UTC, bitscuit commented on cp3pt0-deployment/setup_singleton.sh
> +    create_subscription "ibm-licensing-operator-app" "ibm-licensing" "$CHANNEL" "ibm-licensing-operator" "${LICENSING_SOURCE}" "${SOURCE_NS}" "${INSTALL_MODE}"
Licensing uses master branch for CP 3.0, and the name was changed there

2023-03-24 02:04 UTC, Daniel-Fan commented on cp3pt0-deployment/migrate_singleton.sh
> +        delete_operator "ibm-cert-manager-operator" "$CONTROL_NS"
I think this is only for the scenario where cert-manager is installed in the same namespace as ODLM. In other word, this is an in-place upgrade for a single shared CS.

So we just totally uninstall existing cert-manager and re-install it in All Namespace Mode.

The other part about `delegate_cp2_cert_manager.sh` covers the dedicated CP2 instance case where we only deactivate the CP2 cert-manager and re-install `v4.0` version of cert-manager in All namespace Mode.

But I think users might this script standalone for migration of singleton services, I will refine the logic here

2023-03-24 18:24 UTC, bitscuit approved these changes
/lgtm

2023-03-24 18:24 UTC, merged