Create isolate.sh
IBM/ibm-common-service-operator pull request #1129
Opened 2023-04-06 15:30 UTC by bluzarraga

Currently designed for two runs. The first is to pause and the second is to restart the original cs instance
first called with `./isolate.sh --original-cs-ns <cs instance namespace> --control-ns <desired control namespace> --excluded-ns <comma separated list of namespaces to exclude from new common-service-maps>`
- gather parameters
- pause cs in original instance
- generate common-service-maps cm in kube-public

second `./isolate.sh --original-cs-ns <cs instance namespace> -r`
- check common-service-maps cm
- uninstall singletons
- restart original cs instance

Testing instructions:
- setup environment with preferably 3 cp namespaces sharing one cs (more cp namespaces, more combinations of excluded namespaces you can try)
- run isolate.sh script with varying combinations of excluded namespaces
    - between each run, if you delete the common-service-maps (after verifying it of course) and rescale ODLM and cs operator to 1, you can rerun the test "from scratch." This will let you test multiple combinations with minimal effort resetting the environment
- after verifying that the config map generated is correct, run the script with `-r` (shown above) and confirm pods start up as expected

Notes: 
- The generated csmaps will include the original cs namespace. This does not have any adverse impacts.
- if you run the restart after excluding some namespaces, pods in the excluded namespaces will be cutoff from common services. Expect those pods to fail or otherwise not function properly

Some outstanding changes to be made as of opening this pr:
- ensure ODLM sub `ISOLATED_MODE` value set to "true"
- error handling for excluded namespace not being set
- do not require control namespace to be set for `-r` option
- smaller tweaks based on feedback

2023-04-06 21:26 UTC, Daniel-Fan approved these changes

2023-04-06 23:01 UTC, bitscuit requested changes
Suggest change to running script only once so it should generate cs-maps and then restart installer operators to get v3 cert-manager installed into control namespace quickly.

2023-04-10 18:17 UTC, bluzarraga commented
Added a couple things today:
- ability to insert namespaces that are not already included in the namespace-scope cm. These namespaces do not have to already exist, the script will create them.
- Run isolate one time (no pause/resume split)
- output the namespace-scope cm that is being used for csmaps creation
- can run multiple times (assuming only one requested-from/map-to pairing)
    - this is done by deleting the existing csmaps cm and creating a fresh one
    - the cm is deleted after the pause to prevent it from interfering with namespace collection process

2023-04-10 21:39 UTC, bitscuit commented on isolate.sh
> +}
maintain consistency, newlines after function blocks

2023-04-11 14:12 UTC, bitscuit requested changes

2023-04-11 14:12 UTC, bitscuit commented on isolate.sh
> +}
need newline here after function block

2023-04-11 14:12 UTC, bitscuit commented on isolate.sh
> +}
need newline here after function block

2023-04-11 14:12 UTC, bitscuit commented on isolate.sh
> +}
need newline here after function block

2023-04-11 14:12 UTC, bitscuit commented on isolate.sh
> +}
need newline here after function block

2023-04-11 14:24 UTC, bitscuit approved these changes
/lgtm

2023-04-11 14:25 UTC, merged