add cert manager smoke test to setup singleton and preload data
IBM/ibm-common-service-operator pull request #1382
Opened 2023-07-24 19:43 UTC by bluzarraga

For issue 59713, added a wait for cert manager operand webhook to come ready to setup singleton and then a smoke test where it tries to create a test issuer and certificate. This was added to the end of the script. Added just the smoke test to preload data's prereqs section so the script will error out if these items cannot be created

Testing setup singleton:
- run setup singleton to fresh install cert manager
- verify script completes and the success message "Cert manager is ready." appears at the end of the script

testing preload:
- before installing cert manager, run the script
- verify the script errors out during prereqs with the message: "Failed to create test issuer. Verify cert manager is installed and ready on the cluster then re-run the preload script."
- Install cert manager
- wait for it to come ready
- run preload again, verify the preload checks complete
- Note: you do not need to have any cs installed for the preload script to complete prereq checks. It will error out after the part we are looking at (which is expected).

2023-08-15 05:14 UTC, Daniel-Fan requested changes
Could we use full qualified resource name to distinguish `v1alpha1` version of issuer.

Also I am wondering if we should use `$CERT_MANAGER_NAMESPACE` to deploy test issuer, since `$OPERATOR_NS` is optional, and it is only used for v3.x migration.

2023-08-15 05:14 UTC, Daniel-Fan commented on cp3pt0-deployment/setup_singleton.sh
> +    return_value_cert=$(${OC} get certificate -n $OPERATOR_NS --ignore-not-found | grep test-certificate || echo "false")
```suggestion
    return_value_cert=$(${OC} get certificate.v1.cert-manager.io -n $CERT_MANAGER_NAMESPACE --ignore-not-found | grep test-certificate || echo "false")
```

2023-08-15 05:14 UTC, Daniel-Fan commented on cp3pt0-deployment/setup_singleton.sh
> +      ${OC} delete issuer test-issuer -n $OPERATOR_NS --ignore-not-found
```suggestion
      ${OC} delete issuer.v1.cert-manager.io test-issuer -n $CERT_MANAGER_NAMESPACE --ignore-not-found
```

2023-08-15 05:14 UTC, Daniel-Fan commented on cp3pt0-deployment/setup_singleton.sh
> +      ${OC} delete issuer test-issuer -n $OPERATOR_NS --ignore-not-found
```suggestion
      ${OC} delete certificate.v1.cert-manager.io test-certificate -n $CERT_MANAGER_NAMESPACE --ignore-not-found
      ${OC} delete issuer.v1.cert-manager.io test-issuer -n $CERT_MANAGER_NAMESPACE --ignore-not-found
```

2023-08-15 05:14 UTC, Daniel-Fan commented on preload_data.sh
> +  return_value_issuer=$(${OC} get issuer -n $FROM_NAMESPACE --ignore-not-found | grep test-issuer || echo "false")
```suggestion
  return_value_issuer=$(${OC} get issuer.v1.cert-manager.io -n $FROM_NAMESPACE --ignore-not-found | grep test-issuer || echo "false")
```

2023-08-15 05:14 UTC, Daniel-Fan commented on preload_data.sh
> +    return_value_cert=$(${OC} get certificate -n $FROM_NAMESPACE --ignore-not-found | grep test-certificate || echo "false")
```suggestion
    return_value_cert=$(${OC} get certificate.v1.cert-manager.io -n $FROM_NAMESPACE --ignore-not-found | grep test-certificate || echo "false")
```

2023-08-15 05:14 UTC, Daniel-Fan commented on preload_data.sh
> +      ${OC} delete issuer test-issuer -n $OPERATOR_NS --ignore-not-found
```suggestion
      ${OC} delete issuer.v1.cert-manager.io test-issuer -n $FROM_NAMESPACE --ignore-not-found
```

2023-08-15 05:14 UTC, Daniel-Fan commented on preload_data.sh
> +      ${OC} delete issuer test-issuer -n $FROM_NAMESPACE --ignore-not-found
```suggestion
      ${OC} delete certificate.v1.cert-manager.io test-certificate -n $FROM_NAMESPACE --ignore-not-found
      ${OC} delete issuer.v1.cert-manager.io test-issuer -n $FROM_NAMESPACE --ignore-not-found
```

2023-08-15 05:14 UTC, Daniel-Fan commented on cp3pt0-deployment/setup_singleton.sh
> +  namespace: $OPERATOR_NS
```suggestion
  namespace: $CERT_MANAGER_NAMESPACE
```

2023-08-15 05:14 UTC, Daniel-Fan commented on cp3pt0-deployment/setup_singleton.sh
> +  namespace: $OPERATOR_NS
```suggestion
  namespace: $CERT_MANAGER_NAMESPACE
```

2023-08-15 05:16 UTC, Daniel-Fan requested changes

2023-08-15 05:16 UTC, Daniel-Fan commented on cp3pt0-deployment/setup_singleton.sh
> +  debug1 "Creating test issuer in namespace $OPERATOR_NS."
```suggestion
  debug1 "Creating test issuer in namespace $CERT_MANAGER_NAMESPACE."
```

2023-08-15 05:16 UTC, Daniel-Fan commented on cp3pt0-deployment/setup_singleton.sh
> +    debug1 "Creating test certificate in namespace $OPERATOR_NS."
```suggestion
    debug1 "Creating test certificate in namespace $CERT_MANAGER_NAMESPACE."
```

2023-09-15 19:43 UTC, bluzarraga commented
Tested on amd64 successfully after making recommended changes listed above.
Running preload without installing cert manager:
```
[root@api.admits.cp.fyre.ibm.com ibm-common-service-operator]# ./preload_data.sh --original-cs-ns cs --services-ns test-ns -v 1
No resources found in cs namespace.
[INFO] Checking cert manager readiness.
[DEBUG] Creating test issuer in namespace cs.
error: resource mapping not found for name: "test-issuer" namespace: "cs" from "STDIN": no matches for kind "Issuer" in version "cert-manager.io/v1"
ensure CRDs are installed first
error: the server doesn't have a resource type "issuer"
[✘] Failed to create test issuer. Verify cert manager is installed and ready on the cluster then re-run the preload script.
```
Output as expected

Running setup singleton:
```
...
[✔] Pod cert-manager-webhook is running.

issuer.cert-manager.io/test-issuer created
certificate.cert-manager.io/test-certificate created
certificate.cert-manager.io "test-certificate" deleted
issuer.cert-manager.io "test-issuer" deleted
[✔] Cert manager is ready.
```
Output as expected

Running preload again after cert manager is installed:
```
[root@api.admits.cp.fyre.ibm.com ibm-common-service-operator]# ./preload_data.sh --original-cs-ns cs --services-ns test-ns -v 1
[INFO] Checking cert manager readiness.
[DEBUG] Creating test issuer in namespace cs.
issuer.cert-manager.io/test-issuer created
[DEBUG] Creating test certificate in namespace cs.
certificate.cert-manager.io/test-certificate created
certificate.cert-manager.io "test-certificate" deleted
issuer.cert-manager.io "test-issuer" deleted
[✔] Cert manager is ready, preload can proceed.
...
```
Output as expected, script completed successfully after

Scripts ready for re-review

2023-09-29 18:21 UTC, Daniel-Fan approved these changes
/lgtm

2023-09-29 18:22 UTC, merged