migrate LSR scripts first commit
IBM/ibm-common-service-operator pull request #1431
Opened 2023-08-25 08:30 UTC by geforcelive

2023-08-25 14:54 UTC, Daniel-Fan commented
Hi @geforcelive 

May I ask that could we change the base branch to [`scripts-dev` branch](https://github.com/IBM/ibm-common-service-operator/tree/scripts-dev)?

2023-08-29 10:40 UTC, pgodowski requested changes

2023-08-29 10:40 UTC, pgodowski commented on cp3pt0-deployment/common/migrate_singleton.sh
> +          lsr_pvc_status=$("${OC}" get pvc license-service-reporter-pvc -n $LSR_NAMESPACE --no-headers | awk '{print $2}')
why we're checking the status but we're not using it anywhere?

2023-08-29 10:40 UTC, pgodowski commented on cp3pt0-deployment/setup_singleton.sh
> +      namespace: $LSR_NAMESPACE
```suggestion
      namespace: ${LSR_NAMESPACE}
```

2023-08-29 10:40 UTC, pgodowski commented on cp3pt0-deployment/common/migrate_singleton.sh
> +            namespace: $LSR_NAMESPACE
```suggestion
            namespace: ${LSR_NAMESPACE}
```

2023-08-29 10:40 UTC, pgodowski commented on cp3pt0-deployment/common/migrate_singleton.sh
> +            storageClassName: "$LSR_STORAGE_CLASS"
```suggestion
            storageClassName: "${LSR_STORAGE_CLASS}"
```

2023-08-29 10:40 UTC, pgodowski commented on cp3pt0-deployment/common/migrate_singleton.sh
> +          ${OC} create -f TEMP_LSR_PVC_FILE
not consistent use of curly braces for env variable reference

2023-08-30 16:02 UTC, closed without merging